class Solution {
        public ListNode mergeTwoLists(ListNode list1, ListNode list2) {
                ListNode result;
                        if (list1 == null && list2 == null) {
                                    return null;
                                            }
                                                    if (list1 == null || list2 == null) {
                                                                if (list1 == null) {
                                                                                result = list2;
                                                                                                list2 = list2.next;
                                                                                                            } else {
                                                                                                                            result = list1;
                                                                                                                                            list1 = list1.next;
                                                                                                                                                        }
                                                                                                                                                                } else {
                                                                                                                                                                            if (list1.val > list2.val) {
                                                                                                                                                                                            result = list2;
                                                                                                                                                                                                            list2 = list2.next;
                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                        result = list1;
                                                                                                                                                                                                                                                        list1 = list1.next;
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                    mergeAction(list1, list2, result);
                                                                                                                                                                                                                                                                                            return result;
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        void mergeAction(ListNode list1, ListNode list2, ListNode result) {
                                                                                                                                                                                                                                                                                                                if (list1 == null && list2 == null) {
                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                            if (list1 == null || list2 == null) {
                                                                                                                                                                                                                                                                                                                                                        if (list1 == null) { 
                                                                                                                                                                                                                                                                                                                                                                        result.next = list2;
                                                                                                                                                                                                                                                                                                                                                                                        list2 = list2.next;
                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                    result.next = list1;
                                                                                                                                                                                                                                                                                                                                                                                                                                    list1 = list1.next;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (list1.val > list2.val) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result.next = list2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    list2 = list2.next;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                result.next = list1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                list1 = list1.next;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mergeAction(list1, list2, result.next);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
}