class Solution {
        /* 
              0.     1.    2.    3.    4.    5.    6
                   [1,1],[2,3],[2,3],[1,1],[1,1],[1,1],[1,2]]    
                           
                                 0 
                                       h = 1 + ( 3 +  ( 3 + (1+  (1+ (1 + 2 <- 0
                                                                           [h3] <-2 
                                                                                                               (1,2) <- 0
                                                                                                                                                    [h2]
                                                                                                                                                                                       --------
                                                                                                                                                                                                                           min = h2  
                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                    */
                                                                                                                                                                                                                                                                                                                        int [] m; 
                                                                                                                                                                                                                                                                                                                            public int minHeightShelves(int[][] books, int shelfWidth) {
                                                                                                                                                                                                                                                                                                                                     m  = new int [books.length];

                                                                                                                                                                                                                                                                                                                                            int minHight = dpHelp(books,  shelfWidth, 0);
                                                                                                                                                                                                                                                                                                                                                   return minHight;
                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                           public int dpHelp(int[][] books, int shelfWidth, int i){
                                                                                                                                                                                                                                                                                                                                                                 if(i >= books.length)  return 0;
                                                                                                                                                                                                                                                                                                                                                                       if(m[i] > 0) return m[i];
                                                                                                                                                                                                                                                                                                                                                                             int minTotalHight = Integer.MAX_VALUE;
                                                                                                                                                                                                                                                                                                                                                                                   int width = 0;
                                                                                                                                                                                                                                                                                                                                                                                         int currentHight = 0;
                                                                                                                                                                                                                                                                                                                                                                                               for(int j=i; j<books.length; j++){
                                                                                                                                                                                                                                                                                                                                                                                                         width += books[j][0];
                                                                                                                                                                                                                                                                                                                                                                                                                   if(width > shelfWidth) 
                                                                                                                                                                                                                                                                                                                                                                                                                               break;

                                                                                                                                                                                                                                                                                                                                                                                                                                         currentHight = Math.max(currentHight, books[j][1]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                   int tempTotalHeight = currentHight + dpHelp(books, shelfWidth, j+1); 
                                                                                                                                                                                                                                                                                                                                                                                                                                                             minTotalHight = Math.min(tempTotalHeight, minTotalHight);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if(minTotalHight == Integer.MAX_VALUE) minTotalHight = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             m[i] = minTotalHight;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return minTotalHight;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
}